# Stage 1: Use an official Node.js runtime as a parent image
# Using a specific version for consistency
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies inside the container
RUN npm install

# Copy the rest of your application code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Define the command to run your app
CMD [ "node", "index.js" ]
